"""Error code constants for MagicSquare contracts."""

E_MATRIX_SIZE = "E_MATRIX_SIZE"
E_BLANK_COUNT = "E_BLANK_COUNT"
E_VALUE_RANGE = "E_VALUE_RANGE"
E_DUPLICATE_NONZERO = "E_DUPLICATE_NONZERO"
E_OUTPUT_FORMAT = "E_OUTPUT_FORMAT"
E_NO_VALID_COMBINATION = "E_NO_VALID_COMBINATION"

